<?php

$products = [
    ['name' => 'iPhone X',
    'category_id' => 1,
    'brand_id' => 1,
    'photo' => 'https://images-na.ssl-images-amazon.com/images/I/61RTtsq2YzL.jpg',
    'price' => 25000, 
    'status' => true, 
    'description' => 'Дисплей Super Retina HD. Процессор A11 Bionic с 64-битной архитектурой. Двойная камера 12 Мп с широкоугольным и телеобъективом.'], 
    
    ['name' => 'iPhone 12',
    'category_id' => 1,
    'brand_id' => 1,
    'photo' => 'https://www.insidehook.com/wp-content/uploads/2020/08/iphone.jpg',
    'price' => 41500, 
    'status' => true, 
    'description' => 'Дисплей OLED, на всю переднюю панель, диагональ 6,1 дюйма. Чип A14 Bionic.'], 
    
    ['name' => 'Huawei Mate 50',
    'category_id' => 1,
    'brand_id' => 3,
    'photo' => 'https://gizchina.it/wp-content/uploads/2021/02/mate-50-pro-clone-mate-40-pro.jpg',
    'price' => 49200, 
    'status' => true, 
    'description' => 'Операционная система HarmonyOS. Графический ускоритель Adreno 730'], 
    
    ['name' => 'MacBook Air 13',
    'category_id' => 2,
    'brand_id' => 1,
    'photo' => 'https://d1eh9yux7w8iql.cloudfront.net/product_images/1562824175.27.jpg',
    'price' => 77700, 
    'status' => true, 
    'description' => 'Видеокарта Apple M1 (7 ядер). Тип матрицы IPS. Диагональ 13'], 
    
    ['name' => 'Galaxy Book NP750',
    'category_id' => 2,
    'brand_id' => 2,
    'photo' => 'https://static.onlinetrade.ru/img/items/b/noutbuk_samsung_galaxy_book_np750_i3_1115g4_1.7ghz_8gb_ddr4_256gb_ssd_noodd_uhdg_15.6_amoled_fhd_60hz_300nits_cr_microsd_engkb_w10h_mystic_blue_np750xda_kc1it__2461181_1.jpg',
    'price' => 73700, 
    'status' => true, 
    'description' => 'Ноутбук Samsung Galaxy Book NP750 снабжен ярким 15.6-дюймовым экраном, энергоэффективным процессором Intel Core i7 1165G7 (Tiger Lake) 2.8 ГГц, имеет хорошую видеокарту Intel Iris Xe Graphics.'], 
    
    ['name' => 'Galaxy Chromebook',
    'category_id' => 2,
    'brand_id' => 2,
    'photo' => 'https://m.media-amazon.com/images/I/71G0wi+I5yL.jpg',
    'price' => 90000, 
    'status' => true, 
    'description' => 'Производительность Galaxy Chromebook обеспечивают процессоры Intel 10-го поколения i5-10210U. Максимальный объем ОЗУ трансформера составляет 16 ГБ, а вместимость накопителя — до 1 ТБ.'], 
    
    ['name' => 'Huawei Freebuds 4i',
    'category_id' => 3,
    'brand_id' => 3,
    'photo' => 'https://consumer-img.huawei.com/content/dam/huawei-cbg-site/common/mkt/pdp/audio/freebuds4i/img7/huawei-freebuds-series.jpg',
    'price' => 6000, 
    'status' => true, 
    'description' => 'Активное шумоподавление. 10 часов непрерывного воспроизведения'],

    ['name' => 'Galaxy buds 2',
    'category_id' => 3,
    'brand_id' => 2,
    'photo' => 'https://cifra-shop.ru/image/cache/catalog/product/5/uzitvhoon71ye88_29d4292d-1400x1000.jpg',
    'price' => 10990, 
    'status' => true, 
    'description' => 'Двухполосные динамики. Интеллектуальная передача голоса'], 

    ['name' => 'EO-IC500',
    'category_id' => 3,
    'brand_id' => 2,
    'photo' => 'https://mobisfera.ru/static/965/big/965844461012144.jpg',
    'price' => 4700, 
    'status' => true, 
    'description' => 'Проводная стереогарнитура Samsung ANC Earphone примечательна наличием системы активного подавления шума.'], 
];
