<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Добавить новый продукт</h1>
    <form action="/" method="post">
        <input type="text" placeholder="Название" name="name">
        <input type="text" placeholder="Категория" name="category">
        <button type="submit">Добавить</button>
    </form>
</body>
</html>