<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1>Редактировать товар</h1>
    <h3><?= $flash ?></h3>
    <form action="/table/<?= $product['id'] ?>" method="post">
        <input type="text" placeholder="Название" name="name" value="<?= $product['name'] ?>">
        <input type="text" placeholder="Ссылка на фото" name="photo" value="<?= $product['photo'] ?>">
        <input type="text" placeholder="Цена" name="price" value="<?= $product['price'] ?>">
        <input type="text" placeholder="Описание товара" name="description" value="<?= $product['description'] ?>">
        <br>
        <br>
        <label for="category_select">Выберете категорию</label>
        <select name="category" id="category_select">
            <option value="">-- Категории --</option>
            <option value="1">Телефон</option>
            <option value="2">Ноутбук</option>
            <option value="3">Наушники</option>
        </select>
        <label for="brand_select">Выберете бренд</label>
        <select name="brand" id="brand_select">
            <option value="">-- Бренд --</option>
            <option value="1">apple</option>
            <option value="2">samsung</option>
            <option value="3">Huawei</option>
        </select>
        </select>
        <label for="status_select">Выберете статус</label>
        <select name="status" id="status_select">

            <option value='1'>вкл</option>
            <option value='0'>выкл</option>
        </select>
        <button type="submit">Добавить изменения</button>
    </form>
</body>
</html>