<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a> <?= $products['name'] ?></a>
    <h1>Список продуктов</h1>
    <h3>Отфильтровать по:</h3>
    <form action="/table/filter" method="post">
    <input type="text" placeholder="Название" name="name">
    <input type="text" placeholder="Категория" name="category">

    <button type="submit">Фильтровать</button>
    </form>
    <table>
        <tbody>
            <tr>
                <th>Название</th>
                <th>Категория</th>
                <th>Бренд</th>
                <th>Фото</th>
                <th>URL</th>
                <th>Цена</th>
                <th>Статус</th>
                <th>Описание</th>
            </tr>
            <?php foreach ($products as $product) : ?>
            <tr>
                <td><?= $product['name'] ?></td>
                <td><?= $product['category'] ?></td>
                <td><?= $product['Brand'] ?></td>
                <td><img src="<?= $product['photo'] ?>" width="150" alt="<?= $product['name'] ?>"></td>
                <td><a href="<?= $product['url'] ?>"><?= $product['name'] ?></a></td>
                <td><?= $product['price'] ?></td>
                <td><?= $product['status'] ?></td>
                <td><?= $product['description'] ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</body>
</html>