<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="/">Добавить новый товар</a>
    <h1>Список товаров</h1>

    <h3>Отфильтровать по:</h3>
    <form action="/table" method="post">
        <input type="text" placeholder="Название" name="name" value="<?= $properties['name']?>">
        <label for="category_select">Выберете категорию</label>
        <select name="category" id="category_select">
            <option value="" disabled selected>-- Категории --</option>
            <option value="1">Телефон</option>
            <option value="2">Ноутбук</option>
            <option value="3">Наушники</option>
        </select>
        <label for="brand_select">Выберете бренд</label>
        <select name="brand" id="brand_select">
            <option value="" disabled selected>-- Бренд --</option>
            <option value="1">apple</option>
            <option value="2">samsung</option>
            <option value="3">Huawei</option>
        </select>
        <input type="text" placeholder="Цена от" name="price_from" value="<?= $properties['price_from']?>">
        <input type="text" placeholder="Цена до" name="price_to" value="<?= $properties['price_to']?>">
        <button type="submit">Фильтровать</button>
    </form>

    <h3>Сортировать по:</h3>
    <form action="/table" method="post">
        <select name="sort" id="sort_select">
                <option value="" disabled selected>-- Сортировать по --</option>
                <option value="price">По цене</option>
                <option value="name">По названию</option>
                <option value="created_at">По новизне</option>
            </select>
            <button type="submit">Сортировать</button>
        </form>
    <table>
        <tbody>
            <tr>
                <th>Название</th>
                <th>Категория</th>
                <th>Бренд</th>
                <th>Фото</th>
                <th>URL</th>
                <th>Цена</th>
                <th>Статус</th>
                <th>Описание</th>
                <th>Удалить товар</th>
            </tr>
            <?php foreach ($products as $product) : ?>
            <tr>
                <td><?= $product['name'] ?></td>
                <td><?= $product['category'] ?></td>
                <td><?= $product['brand'] ?></td>
                <td><img src="<?= $product['photo'] ?>" width="150" alt="<?= $product['name'] ?>"></td>
                <td><a href="/table/<?= $product['id'] ?>"><?= $product['name'] ?></a></td>
                <td><?= $product['price'] ?></td>
                <td>
                    <form action="/table" method="post">
                        <input type="hidden"  name="status" value="<?= $product['status'] ?>">
                        <input type="hidden"  name="id" value="<?= $product['id'] ?>">
                        <button type="submit"><?= $product['status'] == 1 ? 'вкл': 'выкл' ?></button>
                    </form>
                </td>
                <td><?= $product['description'] ?></td>
                <td>
                    <form action="/table" method="post">
                        <input type="hidden"  name="delete_id" value="<?= $product['id'] ?>">
                        <button type="submit">Удалить</button>
                    </form>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</body>
</html>